version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: my-todo-app
      POSTGRES_PASSWORD: my-todo-app
      POSTGRES_DB: my-todo-app
    restart: always
    networks:
      - my-app
networks:
  my-app:
